name: Push to main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Clean and deploy
        uses: borales/actions-yarn@v4
        with:
          cmd: clean-and-deploy # will run `yarn clean-and-deploy` command
