name: Deploy to Github Pages

permissions: 
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.1.0

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Create CNAME file
        run: echo 'rs-analysis.xyz' > build/CNAME

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
